name: Stryker mutation tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
       - main

jobs:
  stryker-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run StrykerJS
        continue-on-error: true
        id: stryker
        run: |
          yarn stryker run > out

      - name: Print output
        continue-on-error: true
        run: cat out

      - name: Save stryker JS log
        if: failure()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: stryker.log
          path: stryker.log

      - name: Extract stryker score
        run: |
          grep "All files" out > line
          awk '{print $4}' line > fullscore
          awk '{split($0,a,"."); print a[1]}' fullscore > score
          echo $(echo -n 'stryker-score=' && cat score | tr -s '\n') >> $GITHUB_ENV

      - name: Create the Badge for Deploy Rate
        uses: Schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_AUTH_TOKEN }}
          gistID: 9ce1ad7d8e9db99796e782b244eefa4a
          filename: dora-stryker.json
          label: Stryker score
          message: ${{ env.stryker-score }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.stryker-score }}
  
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
            name: mutation-report
            retention-days: 1
            path: reports/mutation/
            overwrite: true